// Helper function to make it so the navbar can be editted here without having to go through all of the pages to do so
// This is the classiest of all JavaScripts
navString =  "  <nav class='navbar navbar-default navbar-static-top'>";
navString += "    <div class='container'>";
navString += "      <div class='navbar-header'>";
navString += "        <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'>";
navString += "          <span class='sr-only'>Toggle navigation</span>";
navString += "          <span class='icon-bar'></span>";
navString += "         <span class='icon-bar'></span>";
navString += "          <span class='icon-bar'></span>";
navString += "        </button>";
navString += "        <a class='navbar-brand' href='index.html'><img src='img/mainLogo.png'></a>";
navString += "      </div>";
navString += "      <div id='navbar' class='navbar-collapse collapse'>";
navString += "        <ul class='nav navbar-nav navbar-right'>";
navString += "          <li class='dropdown'>";
navString += "            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'>About Therapets<span class='caret'></span></a>";
navString += "            <ul class='dropdown-menu'>";
navString += "              <li><a href='speciesInfo.html'>Species Information</a></li>";
navString += "              <li><a href='rules.html'>Rules and FAQ</a></li>";
navString += "              <li><a href='breeding.html'>Breeding</a></li>";
navString += "              <li><a href='theraMagic.html'>Thera Magic</a></li>";
navString += "            </ul>";
navString += "          </li>";
navString += "          <li class='dropdown'>";
navString += "            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'>Beginner's Guide<span class='caret'></span></a>";
navString += "            <ul class='dropdown-menu'>";
navString += "              <li><a href='creationWalkthrough.html'>Creation Walkthrough</a></li>";
navString += "              <li><a href='designApproval.html'>Design Approval</a></li>";
navString += "              <li><a href='activities.html'>Activities</a></li>";
navString += "            </ul>";
navString += "          </li>";
navString += "          <li class='dropdown'>";
navString += "            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'>Game Mechanics<span class='caret'></span></a>";
navString += "            <ul class='dropdown-menu'>";
navString += "              <li><a href='rank.html'>Rank</a></li>";
navString += "              <li><a href='sprinkleGuide.html'>Sprinkle Guide</a></li>";
navString += "              <li><a href='upgrades.html'>Upgrades and Markings</a></li>";
navString += "              <li><a href='magicShop.html'>Magic Shop</a></li>";
navString += "              <li><a href='therapetRooms.html'>Therapet Rooms</a></li>";
navString += "              <li><a href='craftingStation.html'>Crafting Station</a></li>";
navString += "            </ul>";
navString += "          </li>";
navString += "          <li class='dropdown'>";
navString += "            <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'>The World<span class='caret'></span></a>";
navString += "            <ul class='dropdown-menu'>";
navString += "              <li><a href='exploring.html'>Exploring</a></li>";
navString += "              <li><a href='greenhouse.html'>Greenhouse</a></li>";
navString += "            </ul>";
navString += "          </li>";
navString += "        </ul>";
navString += "      </div>";
navString += "    </div>";
navString += "  </nav>";
$("#navbarOutput").html(navString);